version: '3'
services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: >
      mongod --replSet ${REPLICA_SET_NAME}
             --auth
             --keyFile /etc/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    ports:
      - "27017:27017"  # Exposing port 27017 for mongo1

  mongo2:
    image: mongo:6
    container_name: mongo2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: >
      mongod --replSet ${REPLICA_SET_NAME}
             --auth
             --keyFile /etc/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    ports:
      - "27018:27017"  # Exposing port 27018 for mongo2

  mongo3:
    image: mongo:6
    container_name: mongo3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: >
      mongod --replSet ${REPLICA_SET_NAME}
             --auth
             --keyFile /etc/mongo-keyfile
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    ports:
      - "27019:27017"  # Exposing port 27019 for mongo3
