version: '3.8'

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    hostname: mongo1
    ports:
      - 27017:27017
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_REPLICA_SET_NAME=${REPLICA_SET_NAME}
    command: ["--replSet", "${REPLICA_SET_NAME}", "--keyFile", "/etc/mongo-keyfile"]
    restart: always

  mongo2:
    image: mongo:7
    container_name: mongo2
    hostname: mongo2
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["--replSet", "${REPLICA_SET_NAME}", "--keyFile", "/etc/mongo-keyfile"]
    restart: always

  mongo3:
    image: mongo:7
    container_name: mongo3
    hostname: mongo3
    volumes:
      - ./mongo-keyfile:/etc/mongo-keyfile:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["--replSet", "${REPLICA_SET_NAME}", "--keyFile", "/etc/mongo-keyfile"]
    restart: always

networks:
  default:
    name: mongo-net
