name: Deploy MongoDB ReplicaSet to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd mongodb-docker-replica || git clone https://github.com/<your-user>/<your-repo>.git mongodb-docker-replica
            cd mongodb-docker-replica
            git pull origin main
            docker compose down || true
            docker compose up -d --build
          EOF
