name: Deploy MongoDB ReplicaSet to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Git clone or pull
            if [ -d mongodb-docker-replica/.git ]; then
              cd mongodb-docker-replica
              git pull origin main
            else
              sudo rm -rf mongodb-docker-replica
              git clone https://github.com/Abulkalam-Asif/mongodb-docker-replica.git
              cd mongodb-docker-replica
            fi

            # Set required environment variables
            export MONGO_INITDB_ROOT_USERNAME=admin
            export MONGO_INITDB_ROOT_PASSWORD=supersecret
            export REPLICA_SET_NAME=rs0

            # Create key file (not folder!)
            if [ ! -f mongo-keyfile ]; then
              openssl rand -base64 756 > mongo-keyfile
              chmod 400 mongo-keyfile
              chown 999:999 mongo-keyfile
            fi

            # Stop and remove existing containers
            docker compose down || true

            # Start containers with the replica set config
            docker compose up -d --build

            # Wait for containers to become ready
            sleep 10

            # Initialize the replica set if not already initialized
            is_initialized=$(docker exec mongo1 mongosh -u admin -p supersecret --authenticationDatabase admin --quiet --eval "rs.status().ok" || echo "0")
            if [[ "$is_initialized" != "1" ]]; then
              docker exec mongo1 mongosh -u admin -p supersecret --authenticationDatabase admin --eval '
                rs.initiate({
                  _id: "rs0",
                  members: [
                    { _id: 0, host: "mongo1:27017" },
                    { _id: 1, host: "mongo2:27017" },
                    { _id: 2, host: "mongo3:27017" }
                  ]
                });
              '
              sleep 5
            fi

            # Restart containers just to ensure everything is connected properly
            docker restart mongo1 mongo2 mongo3

            # Display replica set status
            docker exec mongo1 mongosh -u admin -p supersecret --authenticationDatabase admin --eval "rs.status()"
          EOF
